// src/components/FormConfiguracao.svelte
<script lang="ts">
  import { createEventDispatcher, onMount } from "svelte";
  import { createConfiguracaoSiteModel } from "../models/ConfiguracaoSiteModel";
  import { createFinanciadorModel } from "../models/FinanciadorModel";
  import { createApoioModel } from "../models/ApoioModel";
  import { controllerAtualizarConfiguracao } from "../controllers/ConfiguracaoController";
  import { controllerUploadImagem } from "../controllers/UploadController";

  export let config = createConfiguracaoSiteModel();
  export let tipo: string = "hero";

  const dispatch = createEventDispatcher();

  // Hero
  let heroTitulo = "";
  let heroSubtitulo = "";

  // Sobre
  let sobreTitulo = "";
  let sobreConteudo = "";
  let sobreMissao = "";
  let sobreVisao = "";

  // Rodapé - contato
  let contatoEmail = "";
  let contatoTelefone = "";
  let contatoWhatsapp = "";

  // Rodapé - endereço
  let enderecoLinha1 = "";
  let enderecoLinha2 = "";
  let enderecoLinha3 = "";
  let enderecoLinha4 = "";
  let enderecoLinha5 = "";

  // Rodapé - redes sociais
  let redesTwitter = "";
  let redesInstagram = "";
  let redesLinkedin = "";

  // Rodapé - parceiros
  let parceiros = "";

  // Rodapé - financiadores
  let financiadores = [];

  // Rodapé - apoios
  let apoios = [];

  let loading: boolean = false;
  let erro: string = "";
  let overlayEl: HTMLDivElement | undefined = undefined;

  $: sectionTitle =
    tipo === "hero"
      ? "Configuração do Hero"
      : tipo === "sobre"
        ? "Configuração do Sobre"
        : "Configuração do Rodapé";

  onMount(() => {
    if (config) {
      heroTitulo = config.heroTitulo || "";
      heroSubtitulo = config.heroSubtitulo || "";
      sobreTitulo = config.sobreTitulo || "";
      sobreConteudo = config.sobreConteudo || "";
      sobreMissao = config.sobreMissao || "";
      sobreVisao = config.sobreVisao || "";
      contatoEmail = config.contatoEmail || "";
      contatoTelefone = config.contatoTelefone || "";
      contatoWhatsapp = config.contatoWhatsapp || "";
      enderecoLinha1 = config.enderecoLinha1 || "";
      enderecoLinha2 = config.enderecoLinha2 || "";
      enderecoLinha3 = config.enderecoLinha3 || "";
      enderecoLinha4 = config.enderecoLinha4 || "";
      enderecoLinha5 = config.enderecoLinha5 || "";
      redesTwitter = config.redesTwitter || "";
      redesInstagram = config.redesInstagram || "";
      redesLinkedin = config.redesLinkedin || "";
      parceiros = config.parceiros || "";
      financiadores = (config.financiadores || []).map(function (f) {
        return Object.assign({}, f, { _file: null, _preview: f.logoUrl || "" });
      });
      apoios = (config.apoios || []).map(function (a) {
        return Object.assign({}, a, { _file: null, _preview: a.logoUrl || "" });
      });
    }
  });

  function handleClose() {
    dispatch("close");
  }

  function handleOverlayClick(e: MouseEvent) {
    if (e.target === overlayEl) {
      handleClose();
    }
  }

  function onDocumentKeydown(e: KeyboardEvent) {
    if (e.key === "Escape") {
      handleClose();
    }
  }

  // Financiador management
  function addFinanciador() {
    const f = createFinanciadorModel();
    f._file = null;
    f._preview = "";
    financiadores = [...financiadores, f];
  }

  function removeFinanciador(index: number) {
    financiadores = financiadores.filter(function (_, i) {
      return i !== index;
    });
  }

  function handleFinanciadorLogoChange(e: Event, index: number) {
    const file = (e.target as HTMLInputElement).files?.[0];
    if (file) {
      financiadores[index]._file = file;
      const reader = new FileReader();
      reader.onload = function (ev: ProgressEvent<FileReader>) {
        financiadores[index]._preview = ev.target?.result as string;
        financiadores = financiadores;
      };
      reader.readAsDataURL(file);
    }
  }

  function removeFinanciadorLogo(index: number) {
    financiadores[index]._file = null;
    financiadores[index]._preview = "";
    financiadores[index].logoUrl = "";
    financiadores = financiadores;
  }

  // Apoio management
  function addApoio() {
    const a = createApoioModel();
    a._file = null;
    a._preview = "";
    apoios = [...apoios, a];
  }

  function removeApoio(index: number) {
    apoios = apoios.filter(function (_, i) {
      return i !== index;
    });
  }

  function handleApoioLogoChange(e: Event, index: number) {
    const file = (e.target as HTMLInputElement).files?.[0];
    if (file) {
      apoios[index]._file = file;
      const reader = new FileReader();
      reader.onload = function (ev: ProgressEvent<FileReader>) {
        apoios[index]._preview = ev.target?.result as string;
        apoios = apoios;
      };
      reader.readAsDataURL(file);
    }
  }

  function removeApoioLogo(index: number) {
    apoios[index]._file = null;
    apoios[index]._preview = "";
    apoios[index].logoUrl = "";
    apoios = apoios;
  }

  function validateForm() {
    if (tipo === "hero" && !heroTitulo.trim()) {
      erro = "O título do hero é obrigatório.";
      return false;
    }
    return true;
  }

  async function handleSubmit() {
    if (!validateForm()) return;

    loading = true;
    erro = "";

    try {
      // Upload financiador logos
      for (let i = 0; i < financiadores.length; i++) {
        if (financiadores[i]._file) {
          try {
            const url = await controllerUploadImagem(financiadores[i]._file);
            financiadores[i].logoUrl = url;
          } catch (uploadErr) {
            erro = "Erro ao enviar logo do financiador.";
            loading = false;
            return;
          }
        }
      }

      // Upload apoio logos
      for (let i = 0; i < apoios.length; i++) {
        if (apoios[i]._file) {
          try {
            const url = await controllerUploadImagem(apoios[i]._file);
            apoios[i].logoUrl = url;
          } catch (uploadErr) {
            erro = "Erro ao enviar logo do apoio.";
            loading = false;
            return;
          }
        }
      }

      const model = createConfiguracaoSiteModel({
        id: config.id,
        heroTitulo: heroTitulo.trim(),
        heroSubtitulo: heroSubtitulo.trim(),
        sobreTitulo: sobreTitulo.trim(),
        sobreConteudo: sobreConteudo.trim(),
        sobreMissao: sobreMissao.trim(),
        sobreVisao: sobreVisao.trim(),
        contatoEmail: contatoEmail.trim(),
        contatoTelefone: contatoTelefone.trim(),
        contatoWhatsapp: contatoWhatsapp.trim(),
        enderecoLinha1: enderecoLinha1.trim(),
        enderecoLinha2: enderecoLinha2.trim(),
        enderecoLinha3: enderecoLinha3.trim(),
        enderecoLinha4: enderecoLinha4.trim(),
        enderecoLinha5: enderecoLinha5.trim(),
        redesTwitter: redesTwitter.trim(),
        redesInstagram: redesInstagram.trim(),
        redesLinkedin: redesLinkedin.trim(),
        parceiros: parceiros.trim(),
        financiadores: financiadores.map(function (f) {
          return createFinanciadorModel({
            id: f.id,
            nome: f.nome,
            logoUrl: f.logoUrl,
            ordem: f.ordem,
            temDestaque: f.temDestaque,
            mostrarLogo: f.mostrarLogo,
          });
        }),
        apoios: apoios.map(function (a) {
          return createApoioModel({
            id: a.id,
            nome: a.nome,
            logoUrl: a.logoUrl,
            ordem: a.ordem,
            temDestaque: a.temDestaque,
            mostrarLogo: a.mostrarLogo,
          });
        }),
      });

      const resultado = await controllerAtualizarConfiguracao(model);

      if (resultado && resultado.sucesso !== false) {
        dispatch("success", { config: resultado.response || model });
        handleClose();
      } else {
        erro =
          (resultado && resultado.mensagem) || "Erro ao salvar configuração.";
      }
    } catch (err) {
      erro = err.message || "Erro ao salvar configuração. Tente novamente.";
    } finally {
      loading = false;
    }
  }

  onMount(() => {
    document.addEventListener("keydown", onDocumentKeydown);
    return () => {
      document.removeEventListener("keydown", onDocumentKeydown);
    };
  });
</script>

<div class="overlay" bind:this={overlayEl} on:click={handleOverlayClick}>
  <div class="modal" on:click|stopPropagation>
    <button class="close-btn" on:click={handleClose} aria-label="Fechar"
      >&times;</button
    >

    <h2 class="modal-title">{sectionTitle}</h2>

    {#if erro}
      <div class="error-msg">{erro}</div>
    {/if}

    <form on:submit|preventDefault={handleSubmit}>
      {#if tipo === "hero"}
        <!-- Hero Section -->
        <div class="field">
          <label for="config-hero-titulo">Título do Hero *</label>
          <input
            id="config-hero-titulo"
            type="text"
            bind:value={heroTitulo}
            placeholder="Título principal"
            disabled={loading}
          />
        </div>
        <div class="field">
          <label for="config-hero-subtitulo">Subtítulo do Hero</label>
          <textarea
            id="config-hero-subtitulo"
            bind:value={heroSubtitulo}
            placeholder="Subtítulo ou descrição"
            disabled={loading}
            rows="3"
          ></textarea>
        </div>
      {:else if tipo === "sobre"}
        <!-- Sobre Section -->
        <div class="field">
          <label for="config-sobre-titulo">Título da Seção Sobre</label>
          <input
            id="config-sobre-titulo"
            type="text"
            bind:value={sobreTitulo}
            placeholder="Título"
            disabled={loading}
          />
        </div>
        <div class="field">
          <label for="config-sobre-conteudo">Conteúdo</label>
          <textarea
            id="config-sobre-conteudo"
            bind:value={sobreConteudo}
            placeholder="Texto sobre a instituição"
            disabled={loading}
            rows="4"
          ></textarea>
        </div>
        <div class="field">
          <label for="config-sobre-missao">Missão</label>
          <textarea
            id="config-sobre-missao"
            bind:value={sobreMissao}
            placeholder="Missão da instituição"
            disabled={loading}
            rows="2"
          ></textarea>
        </div>
        <div class="field">
          <label for="config-sobre-visao">Visão</label>
          <textarea
            id="config-sobre-visao"
            bind:value={sobreVisao}
            placeholder="Visão da instituição"
            disabled={loading}
            rows="2"
          ></textarea>
        </div>
      {:else if tipo === "rodape"}
        <!-- Rodapé Section -->
        <h3 class="section-subtitle">Contato</h3>
        <div class="field-row">
          <div class="field">
            <label for="config-contato-email">Email</label>
            <input
              id="config-contato-email"
              type="email"
              bind:value={contatoEmail}
              placeholder="contato@instituicao.br"
              disabled={loading}
            />
          </div>
          <div class="field">
            <label for="config-contato-telefone">Telefone</label>
            <input
              id="config-contato-telefone"
              type="text"
              bind:value={contatoTelefone}
              placeholder="(71) 99999-9999"
              disabled={loading}
            />
          </div>
        </div>
        <div class="field">
          <label for="config-contato-whatsapp">WhatsApp</label>
          <input
            id="config-contato-whatsapp"
            type="text"
            bind:value={contatoWhatsapp}
            placeholder="Link ou número WhatsApp"
            disabled={loading}
          />
        </div>

        <h3 class="section-subtitle">Endereço</h3>
        <div class="field">
          <label for="config-end-linha1">Linha 1</label>
          <input
            id="config-end-linha1"
            type="text"
            bind:value={enderecoLinha1}
            placeholder="Rua, número"
            disabled={loading}
          />
        </div>
        <div class="field">
          <label for="config-end-linha2">Linha 2</label>
          <input
            id="config-end-linha2"
            type="text"
            bind:value={enderecoLinha2}
            placeholder="Bairro"
            disabled={loading}
          />
        </div>
        <div class="field-row">
          <div class="field">
            <label for="config-end-linha3">Linha 3</label>
            <input
              id="config-end-linha3"
              type="text"
              bind:value={enderecoLinha3}
              placeholder="Cidade"
              disabled={loading}
            />
          </div>
          <div class="field">
            <label for="config-end-linha4">Linha 4</label>
            <input
              id="config-end-linha4"
              type="text"
              bind:value={enderecoLinha4}
              placeholder="Estado, CEP"
              disabled={loading}
            />
          </div>
        </div>
        <div class="field">
          <label for="config-end-linha5">Linha 5</label>
          <input
            id="config-end-linha5"
            type="text"
            bind:value={enderecoLinha5}
            placeholder="País"
            disabled={loading}
          />
        </div>

        <h3 class="section-subtitle">Redes Sociais</h3>
        <div class="field-row">
          <div class="field">
            <label for="config-redes-twitter">Twitter / X</label>
            <input
              id="config-redes-twitter"
              type="url"
              bind:value={redesTwitter}
              placeholder="https://twitter.com/..."
              disabled={loading}
            />
          </div>
          <div class="field">
            <label for="config-redes-instagram">Instagram</label>
            <input
              id="config-redes-instagram"
              type="url"
              bind:value={redesInstagram}
              placeholder="https://instagram.com/..."
              disabled={loading}
            />
          </div>
        </div>
        <div class="field">
          <label for="config-redes-linkedin">LinkedIn</label>
          <input
            id="config-redes-linkedin"
            type="url"
            bind:value={redesLinkedin}
            placeholder="https://linkedin.com/..."
            disabled={loading}
          />
        </div>

        <h3 class="section-subtitle">Parceiros</h3>
        <div class="field">
          <label for="config-parceiros">Texto dos Parceiros</label>
          <textarea
            id="config-parceiros"
            bind:value={parceiros}
            placeholder="Nomes dos parceiros, separados por linha"
            disabled={loading}
            rows="3"
          ></textarea>
        </div>

        <h3 class="section-subtitle">Financiadores</h3>
        {#each financiadores as fin, index}
          <div class="list-item">
            <div class="list-item-fields">
              <div class="field">
                <label>Nome</label>
                <input
                  type="text"
                  bind:value={fin.nome}
                  placeholder="Nome do financiador"
                  disabled={loading}
                />
              </div>
              <div class="field">
                <label>Ordem (Opcional)</label>
                <input
                  type="number"
                  bind:value={fin.ordem}
                  placeholder="0"
                  disabled={loading}
                  min="0"
                />
              </div>
            </div>
            <div class="list-item-logo">
              {#if fin._preview}
                <div class="mini-preview-container">
                  <img src={fin._preview} alt="Logo" class="mini-preview" />
                  <button
                    type="button"
                    class="btn-mini-remove"
                    on:click={() => removeFinanciadorLogo(index)}
                    disabled={loading}>&times;</button
                  >
                </div>
              {/if}
              <input
                type="file"
                accept="image/*"
                on:change={(e) => handleFinanciadorLogoChange(e, index)}
                disabled={loading}
                class="file-input-sm"
              />
            </div>
            <div class="checkbox-group-inline">
              <label class="checkbox-label">
                <input
                  type="checkbox"
                  bind:checked={fin.temDestaque}
                  disabled={loading}
                />
                <span>Destaque</span>
              </label>
              <label class="checkbox-label">
                <input
                  type="checkbox"
                  bind:checked={fin.mostrarLogo}
                  disabled={loading}
                />
                <span>Mostrar Logo</span>
              </label>
            </div>
            <button
              type="button"
              class="btn-remove-item"
              on:click={() => removeFinanciador(index)}
              disabled={loading}>Remover</button
            >
          </div>
        {/each}
        <button
          type="button"
          class="btn-add-item"
          on:click={addFinanciador}
          disabled={loading}>+ Adicionar Financiador</button
        >

        <h3 class="section-subtitle">Apoios</h3>
        {#each apoios as apo, index}
          <div class="list-item">
            <div class="list-item-fields">
              <div class="field">
                <label>Nome</label>
                <input
                  type="text"
                  bind:value={apo.nome}
                  placeholder="Nome do apoio"
                  disabled={loading}
                />
              </div>
              <div class="field">
                <label>Ordem (Opcional)</label>
                <input
                  type="number"
                  bind:value={apo.ordem}
                  placeholder="0"
                  disabled={loading}
                  min="0"
                />
              </div>
            </div>
            <div class="list-item-logo">
              {#if apo._preview}
                <div class="mini-preview-container">
                  <img src={apo._preview} alt="Logo" class="mini-preview" />
                  <button
                    type="button"
                    class="btn-mini-remove"
                    on:click={() => removeApoioLogo(index)}
                    disabled={loading}>&times;</button
                  >
                </div>
              {/if}
              <input
                type="file"
                accept="image/*"
                on:change={(e) => handleApoioLogoChange(e, index)}
                disabled={loading}
                class="file-input-sm"
              />
            </div>
            <div class="checkbox-group-inline">
              <label class="checkbox-label">
                <input
                  type="checkbox"
                  bind:checked={apo.temDestaque}
                  disabled={loading}
                />
                <span>Destaque</span>
              </label>
              <label class="checkbox-label">
                <input
                  type="checkbox"
                  bind:checked={apo.mostrarLogo}
                  disabled={loading}
                />
                <span>Mostrar Logo</span>
              </label>
            </div>
            <button
              type="button"
              class="btn-remove-item"
              on:click={() => removeApoio(index)}
              disabled={loading}>Remover</button
            >
          </div>
        {/each}
        <button
          type="button"
          class="btn-add-item"
          on:click={addApoio}
          disabled={loading}>+ Adicionar Apoio</button
        >
      {/if}

      <div class="btn-group">
        <button
          type="button"
          class="btn-cancel"
          on:click={handleClose}
          disabled={loading}>Cancelar</button
        >
        <button type="submit" class="btn-submit" disabled={loading}>
          {#if loading}
            <span class="spinner"></span> Salvando...
          {:else}
            Salvar
          {/if}
        </button>
      </div>
    </form>
  </div>
</div>

<style>
  .overlay {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: rgba(0, 0, 0, 0.7);
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 1002;
    overflow-y: auto;
    padding: 20px;
  }

  .modal {
    background-color: #ffffff;
    padding: 40px;
    border-radius: 8px;
    max-width: 1200px;
    width: 100%;
    max-height: 98vh;
    overflow-y: auto;
    position: relative;
  }

  .close-btn {
    position: absolute;
    top: 20px;
    right: 20px;
    background: none;
    border: none;
    font-size: 24px;
    cursor: pointer;
    color: #4a5d3c;
    font-weight: bold;
  }

  .modal-title {
    margin: 0 0 25px 0;
    color: #4a5d3c;
    font-size: 28px;
    font-weight: bold;
  }

  .section-subtitle {
    font-size: 20px;
    color: #4a5d3c;
    margin-top: 30px;
    margin-bottom: 15px;
    border-bottom: 2px solid #e8ddc5;
    padding-bottom: 8px;
    font-weight: normal; /* In TSX it doesn't specify bold, but h3 browser default is bold. Leave browser default. */
  }

  .error-msg {
    background: #fef2f2;
    border: 1px solid #fca5a5;
    color: #dc2626;
    padding: 10px 14px;
    border-radius: 4px;
    font-size: 14px;
    margin-bottom: 20px;
  }

  .field {
    margin-bottom: 0;
  }

  .field label {
    display: block;
    margin-bottom: 8px;
    color: #4a5d3c;
    font-weight: bold;
    font-size: 14px;
  }

  .field input,
  .field textarea,
  .field select {
    width: 100%;
    padding: 12px;
    margin-bottom: 20px;
    border: 2px solid #e8ddc5;
    border-radius: 4px;
    font-size: 14px;
    box-sizing: border-box;
    font-family: inherit;
    background-color: #ffffff;
  }

  .field input:focus,
  .field textarea:focus,
  .field select:focus {
    outline: none;
    border-color: #4a5d3c;
  }

  .field input:disabled,
  .field textarea:disabled,
  .field select:disabled {
    background: #f3f4f6;
    cursor: not-allowed;
  }

  .field textarea {
    min-height: 100px;
    resize: vertical;
  }

  .field-row {
    display: flex;
    gap: 16px;
  }

  .field-row .field {
    flex: 1;
  }

  .list-item {
    border: 1px solid #e8ddc5;
    padding: 15px;
    border-radius: 6px;
    margin-bottom: 15px;
    background-color: #fef9f0;
  }

  .list-item-fields {
    display: flex;
    gap: 15px;
  }

  .list-item-fields .field {
    flex: 1;
  }

  .list-item-logo {
    margin-bottom: 20px; /* Input already has 20px mb but wrap adds spacing */
  }

  .mini-preview-container {
    position: relative;
    display: inline-block;
    margin-bottom: 10px;
  }

  .mini-preview {
    max-width: 100px;
    display: block;
  }

  .btn-mini-remove {
    position: absolute;
    top: -8px;
    right: -8px;
    background: #dc2626;
    color: #fff;
    border: none;
    border-radius: 50%;
    width: 20px;
    height: 20px;
    font-size: 12px;
    line-height: 1;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .file-input-sm {
    /* Base input style applies here */
  }

  .checkbox-group-inline {
    display: flex;
    gap: 16px;
    margin-bottom: 20px;
  }

  .checkbox-label {
    display: flex;
    align-items: center;
    gap: 8px;
    color: #4a5d3c;
    font-weight: bold;
    font-size: 14px;
    cursor: pointer;
  }

  .checkbox-label input[type="checkbox"] {
    width: auto;
    margin-bottom: 0;
  }

  .btn-remove-item {
    color: red;
    border: none;
    background: none;
    cursor: pointer;
    padding: 0;
    font-size: 14px;
    margin-bottom: 15px;
  }

  .btn-add-item {
    background-color: #7a8a6a;
    color: #ffffff;
    border: none;
    border-radius: 4px;
    padding: 10px 20px;
    font-size: 16px;
    font-weight: bold;
    cursor: pointer;
    margin-bottom: 20px;
    display: block;
  }

  .btn-group {
    display: flex;
    gap: 10px;
    margin-top: 30px;
    position: sticky;
    bottom: -40px; /* Offset the 40px padding of modal */
    background-color: #ffffff;
    padding: 20px 0;
  }

  .btn-cancel {
    flex: 1;
    padding: 14px;
    border: 2px solid #4a5d3c;
    border-radius: 4px;
    font-size: 16px;
    cursor: pointer;
    background-color: #ffffff;
    color: #4a5d3c;
    font-weight: bold;
  }

  .btn-cancel:disabled {
    opacity: 0.7;
    cursor: not-allowed;
  }

  .btn-submit {
    flex: 1;
    padding: 14px;
    border: none;
    border-radius: 4px;
    font-size: 16px;
    cursor: pointer;
    background-color: #4a5d3c;
    color: #ffffff;
    font-weight: bold;
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 8px;
  }

  .btn-submit:disabled {
    opacity: 0.7;
    cursor: not-allowed;
  }

  .spinner {
    display: inline-block;
    width: 16px;
    height: 16px;
    border: 2px solid rgba(255, 255, 255, 0.3);
    border-top-color: #ffffff;
    border-radius: 50%;
    animation: spin 0.6s linear infinite;
  }

  @keyframes spin {
    to {
      transform: rotate(360deg);
    }
  }
</style>

// src/app/components/FormConfiguracao.tsx
import React from 'react';
import { ConfiguracaoSiteModel } from '../models/ConfiguracaoSiteModel';
import { FinanciadorModel } from '../models/FinanciadorModel';
import { ApoioModel } from '../models/ApoioModel';
import { controllerAtualizarConfiguracao } from '../controllers/ConfiguracaoController';
import { controllerUploadImagem } from '../controllers/UploadController';

type CSS = React.CSSProperties;

const overlayStyle: CSS = {
  position: 'fixed',
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
  backgroundColor: 'rgba(0, 0, 0, 0.7)',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  zIndex: 1002,
  overflowY: 'auto',
  padding: '20px',
};

const modalStyle: CSS = {
  backgroundColor: '#ffffff',
  padding: '40px',
  borderRadius: '8px',
  maxWidth: '800px',
  width: '100%',
  maxHeight: '90vh',
  overflowY: 'auto',
};

const titleStyle: CSS = {
  margin: '0 0 25px 0',
  color: '#4a5d3c',
  fontSize: '28px',
};

const sectionTitleStyle: CSS = {
  fontSize: '20px',
  color: '#4a5d3c',
  marginTop: '30px',
  marginBottom: '15px',
  borderBottom: '2px solid #e8ddc5',
  paddingBottom: '8px',
};

const labelStyle: CSS = {
  display: 'block',
  marginBottom: '8px',
  color: '#4a5d3c',
  fontWeight: 'bold',
  fontSize: '14px',
};

const inputStyle: CSS = {
  width: '100%',
  padding: '12px',
  marginBottom: '20px',
  border: '2px solid #e8ddc5',
  borderRadius: '4px',
  fontSize: '14px',
  boxSizing: 'border-box',
};

const textareaStyle: CSS = {
  width: '100%',
  padding: '12px',
  marginBottom: '20px',
  border: '2px solid #e8ddc5',
  borderRadius: '4px',
  fontSize: '14px',
  boxSizing: 'border-box',
  minHeight: '100px',
  fontFamily: 'inherit',
};

const buttonContainerStyle: CSS = {
  display: 'flex',
  gap: '10px',
  marginTop: '30px',
  position: 'sticky',
  bottom: 0,
  backgroundColor: '#ffffff',
  padding: '20px 0',
};

const buttonStyle: CSS = {
  flex: 1,
  padding: '14px',
  border: 'none',
  borderRadius: '4px',
  fontSize: '16px',
  cursor: 'pointer',
  backgroundColor: '#4a5d3c',
  color: '#ffffff',
  fontWeight: 'bold',
};

const cancelButtonStyle: CSS = {
  flex: 1,
  padding: '14px',
  border: '2px solid #4a5d3c',
  borderRadius: '4px',
  fontSize: '16px',
  cursor: 'pointer',
  backgroundColor: '#ffffff',
  color: '#4a5d3c',
  fontWeight: 'bold',
};

export class FormConfiguracao extends React.Component<{
  config: ConfiguracaoSiteModel;
  tipo: 'hero' | 'sobre' | 'rodape';
  onClose: () => void;
  onSuccess: (novaConfig?: ConfiguracaoSiteModel) => void;
}> {
  state = {
    config: (() => {
      const c = Object.assign(new ConfiguracaoSiteModel(), this.props.config);
      for (const k in c) {
        if ((c as any)[k] === null || (c as any)[k] === undefined) {
          if (k !== 'financiadores' && k !== 'apoios' && k !== 'id') {
            (c as any)[k] = '';
          }
        }
      }
      return c;
    })(),
    carregando: false,
    files: {} as { [id: number]: File },
    previewUrls: {} as { [id: number]: string },
  };

  handleLogoFileChange = (e: React.ChangeEvent<HTMLInputElement>, id: number) => {
    if (e.target.files && e.target.files[0]) {
      const file = e.target.files[0];
      const previewUrl = URL.createObjectURL(file);
      this.setState((prevState: any) => ({
        files: { ...prevState.files, [id]: file },
        previewUrls: { ...prevState.previewUrls, [id]: previewUrl }
      }));
    }
  };

  handleSalvar = async () => {
    this.setState({ carregando: true });

    let configToSave = Object.assign(new ConfiguracaoSiteModel(), this.state.config);

    const uploadForArray = async (items: any[]) => {
      const newItems = [...items];
      for (let i = 0; i < newItems.length; i++) {
        const item = newItems[i];
        if ((this.state.files as any)[item.id]) {
          try {
            const url = await controllerUploadImagem((this.state.files as any)[item.id]);
            newItems[i] = { ...item, logoUrl: url };
          } catch (err) {
            alert(`Erro no upload da imagem para ${item.nome || 'item'}`);
            throw err;
          }
        }
      }
      return newItems;
    };

    try {
      configToSave.financiadores = await uploadForArray(configToSave.financiadores || []);
      configToSave.apoios = await uploadForArray(configToSave.apoios || []);
    } catch (err) {
      this.setState({ carregando: false });
      return;
    }

    const result = await controllerAtualizarConfiguracao(configToSave);
    this.setState({ carregando: false });
    this.props.onSuccess(result?.response || configToSave);
    this.props.onClose();
  };

  updateField = (field: keyof ConfiguracaoSiteModel, value: string) => {
    this.setState({
      config: Object.assign(new ConfiguracaoSiteModel(), this.state.config, {
        [field]: value,
      }),
    });
  };

  renderHeroForm = () => {
    const { config } = this.state;

    return (
      <div>
        <label style={labelStyle}>Título Principal</label>
        <input
          type="text"
          style={inputStyle}
          value={config.heroTitulo}
          onChange={(e) => this.updateField('heroTitulo', e.target.value)}
        />

        <label style={labelStyle}>Subtítulo / Descrição</label>
        <textarea
          style={textareaStyle}
          value={config.heroSubtitulo}
          onChange={(e) => this.updateField('heroSubtitulo', e.target.value)}
        />
      </div>
    );
  };

  renderSobreForm = () => {
    const { config } = this.state;

    return (
      <div>
        <label style={labelStyle}>Título da Seção</label>
        <input
          type="text"
          style={inputStyle}
          value={config.sobreTitulo}
          onChange={(e) => this.updateField('sobreTitulo', e.target.value)}
        />

        <label style={labelStyle}>Conteúdo Principal</label>
        <textarea
          style={Object.assign({}, textareaStyle, { minHeight: '150px' })}
          value={config.sobreConteudo}
          onChange={(e) => this.updateField('sobreConteudo', e.target.value)}
        />

        <label style={labelStyle}>Missão</label>
        <textarea
          style={textareaStyle}
          value={config.sobreMissao}
          onChange={(e) => this.updateField('sobreMissao', e.target.value)}
        />

        <label style={labelStyle}>Visão</label>
        <textarea
          style={textareaStyle}
          value={config.sobreVisao}
          onChange={(e) => this.updateField('sobreVisao', e.target.value)}
        />
      </div>
    );
  };

  renderRodapeForm = () => {
    const { config } = this.state;

    const addFinanciador = () => {
      const novo = new FinanciadorModel();
      novo.id = Date.now();
      novo.ordem = (config.financiadores || []).length + 1;
      novo.nome = '';
      novo.temDestaque = true; 
      novo.mostrarLogo = true;
      
      this.setState({
        config: Object.assign(new ConfiguracaoSiteModel(), config, {
          financiadores: [...(config.financiadores || []), novo],
        }),
      });
    };

    const removeFinanciador = (id: number) => {
      this.setState({
        config: Object.assign(new ConfiguracaoSiteModel(), config, {
          financiadores: config.financiadores.filter(f => f.id !== id),
        }),
      });
    };

    const updateFinanciador = (id: number, field: string, value: any) => {
      this.setState({
        config: Object.assign(new ConfiguracaoSiteModel(), config, {
          financiadores: config.financiadores.map(f => f.id === id ? { ...f, [field]: value } : f),
        }),
      });
    };

    const addApoio = () => {
      const novo = new ApoioModel();
      novo.id = Date.now();
      novo.ordem = (config.apoios || []).length + 1;
      novo.nome = '';
      novo.temDestaque = false;
      novo.mostrarLogo = true;
      
      this.setState({
        config: Object.assign(new ConfiguracaoSiteModel(), config, {
          apoios: [...(config.apoios || []), novo],
        }),
      });
    };

    const removeApoio = (id: number) => {
      this.setState({
        config: Object.assign(new ConfiguracaoSiteModel(), config, {
          apoios: config.apoios.filter(f => f.id !== id),
        }),
      });
    };

    const updateApoio = (id: number, field: string, value: any) => {
      this.setState({
        config: Object.assign(new ConfiguracaoSiteModel(), config, {
          apoios: config.apoios.map(f => f.id === id ? { ...f, [field]: value } : f),
        }),
      });
    };

    const renderCard = (f: any, label: string, onUpdate: (id: number, field: string, value: any) => void, onRemove: (id: number) => void) => (
      <div key={f.id} style={{ 
        border: '1px solid #e8ddc5', 
        padding: '15px', 
        borderRadius: '6px', 
        marginBottom: '15px',
        backgroundColor: '#fef9f0'
      }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '10px' }}>
          <span style={{ fontWeight: 'bold' }}>{label}</span>
          <button 
            onClick={() => onRemove(f.id)}
            style={{ color: 'red', border: 'none', background: 'none', cursor: 'pointer' }}
          >
            Remover
          </button>
        </div>
        
        <label style={labelStyle}>Nome</label>
        <input
          type="text"
          style={inputStyle}
          value={f.nome}
          onChange={(e) => onUpdate(f.id, 'nome', e.target.value)}
        />

        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '15px' }}>
          <div>
            <label style={labelStyle}>Ordem</label>
            <input
              type="number"
              style={inputStyle}
              value={f.ordem}
              onChange={(e) => onUpdate(f.id, 'ordem', parseInt(e.target.value))}
            />
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', justifyContent: 'center' }}>
            <label style={{ ...labelStyle, marginBottom: '0', display: 'flex', alignItems: 'center', gap: '8px', cursor: 'pointer' }}>
              <input
                type="checkbox"
                checked={f.temDestaque}
                onChange={(e) => onUpdate(f.id, 'temDestaque', e.target.checked)}
              />
              Em Destaque?
            </label>
          </div>
        </div>

        <label style={labelStyle}>Logo (ou deixe vazio para texto) *</label>
        <input
          type="file"
          accept="image/*"
          style={inputStyle}
          onChange={(e) => this.handleLogoFileChange(e, f.id)}
        />
        {this.state.carregando && (this.state.files as any)[f.id] && <span style={{fontSize: '12px', color: '#666'}}>Enviando imagem...</span>}
        {((this.state.previewUrls as any)[f.id] || f.logoUrl) && (
          <div style={{marginBottom: 10}}>
            <img src={(this.state.previewUrls as any)[f.id] || f.logoUrl} style={{maxWidth: '100px'}} alt="Preview" />
          </div>
        )}
        
        <label style={{ ...labelStyle, display: 'flex', alignItems: 'center', gap: '8px', cursor: 'pointer' }}>
          <input
            type="checkbox"
            checked={f.mostrarLogo}
            onChange={(e) => onUpdate(f.id, 'mostrarLogo', e.target.checked)}
          />
          Exibir Imagem?
        </label>
      </div>
    );

    return (
      <div>
        <div style={sectionTitleStyle}>Contato</div>
        
        <label style={labelStyle}>Email</label>
        <input
          type="email"
          style={inputStyle}
          value={config.contatoEmail}
          onChange={(e) => this.updateField('contatoEmail', e.target.value)}
        />

        <label style={labelStyle}>Telefone</label>
        <input
          type="text"
          style={inputStyle}
          value={config.contatoTelefone}
          onChange={(e) => this.updateField('contatoTelefone', e.target.value)}
        />

        <label style={labelStyle}>WhatsApp</label>
        <input
          type="text"
          style={inputStyle}
          value={config.contatoWhatsapp}
          onChange={(e) => this.updateField('contatoWhatsapp', e.target.value)}
        />

        <div style={sectionTitleStyle}>Endereço</div>
        
        <label style={labelStyle}>Linha 1</label>
        <input
          type="text"
          style={inputStyle}
          value={config.enderecoLinha1}
          onChange={(e) => this.updateField('enderecoLinha1', e.target.value)}
        />

        <label style={labelStyle}>Linha 2</label>
        <input
          type="text"
          style={inputStyle}
          value={config.enderecoLinha2}
          onChange={(e) => this.updateField('enderecoLinha2', e.target.value)}
        />

        <label style={labelStyle}>Linha 3</label>
        <input
          type="text"
          style={inputStyle}
          value={config.enderecoLinha3}
          onChange={(e) => this.updateField('enderecoLinha3', e.target.value)}
        />

        <label style={labelStyle}>Linha 4</label>
        <input
          type="text"
          style={inputStyle}
          value={config.enderecoLinha4}
          onChange={(e) => this.updateField('enderecoLinha4', e.target.value)}
        />

        <label style={labelStyle}>Linha 5</label>
        <input
          type="text"
          style={inputStyle}
          value={config.enderecoLinha5}
          onChange={(e) => this.updateField('enderecoLinha5', e.target.value)}
        />

        <div style={sectionTitleStyle}>Redes Sociais</div>
        
        <label style={labelStyle}>Twitter/X</label>
        <input
          type="url"
          style={inputStyle}
          value={config.redesTwitter}
          onChange={(e) => this.updateField('redesTwitter', e.target.value)}
        />

        <label style={labelStyle}>Instagram</label>
        <input
          type="url"
          style={inputStyle}
          value={config.redesInstagram}
          onChange={(e) => this.updateField('redesInstagram', e.target.value)}
        />

        <label style={labelStyle}>LinkedIn</label>
        <input
          type="url"
          style={inputStyle}
          value={config.redesLinkedin}
          onChange={(e) => this.updateField('redesLinkedin', e.target.value)}
        />

        <div style={sectionTitleStyle}>Parceiros</div>

        <label style={labelStyle}>Lista de Parceiros (separados por vírgula)</label>
        <textarea
          style={textareaStyle}
          value={config.parceiros}
          onChange={(e) => this.updateField('parceiros', e.target.value)}
        />

        <div style={sectionTitleStyle}>Financiamento</div>
        {(config.financiadores || []).map((f, i) => renderCard(f, `Financiador #${i + 1}`, updateFinanciador, removeFinanciador))}
        <button 
          style={{ ...buttonStyle, backgroundColor: '#7a8a6a', marginBottom: '20px', display: 'block', width: 'auto', padding: '10px 20px' }}
          onClick={addFinanciador}
        >
          + Adicionar Financiador
        </button>

        <div style={sectionTitleStyle}>Apoio</div>
        {(config.apoios || []).map((f, i) => renderCard(f, `Apoio #${i + 1}`, updateApoio, removeApoio))}
        <button 
          style={{ ...buttonStyle, backgroundColor: '#7a8a6a', marginBottom: '20px', display: 'block', width: 'auto', padding: '10px 20px' }}
          onClick={addApoio}
        >
          + Adicionar Apoio
        </button>
      </div>
    );
  };

  render() {
    const { onClose, tipo } = this.props;
    const { carregando } = this.state;

    const titulos = {
      hero: 'Editar Texto Principal',
      sobre: 'Editar Sobre o Projeto',
      rodape: 'Editar Informações de Rodapé',
    };

    return (
      <div style={overlayStyle} onClick={onClose}>
        <div style={modalStyle} onClick={(e) => e.stopPropagation()}>
          <h2 style={titleStyle}>{titulos[tipo]}</h2>

          {tipo === 'hero' && this.renderHeroForm()}
          {tipo === 'sobre' && this.renderSobreForm()}
          {tipo === 'rodape' && this.renderRodapeForm()}

          <div style={buttonContainerStyle}>
            <button
              style={cancelButtonStyle}
              onClick={onClose}
              disabled={carregando}
            >
              Cancelar
            </button>
            <button
              style={buttonStyle}
              onClick={this.handleSalvar}
              disabled={carregando}
            >
              {carregando ? 'Salvando...' : 'Salvar'}
            </button>
          </div>
        </div>
      </div>
    );
  }
}
