// src/app/components/CarrosselImagens.tsx
import React from 'react';

type CSS = React.CSSProperties;

interface CarrosselImagensProps {
  imagens: Array<{
    url: string;
    titulo?: string;
    legenda?: string;
  }>;
  altura?: string;
  autoPlay?: boolean;
  intervalo?: number;
}

export class CarrosselImagens extends React.Component<CarrosselImagensProps> {
  state = {
    indiceAtual: 0,
  };

  intervaloId: NodeJS.Timeout | null = null;

  componentDidMount() {
    const { autoPlay = true, intervalo = 5000 } = this.props;
    if (autoPlay && this.props.imagens.length > 1) {
      this.intervaloId = setInterval(this.proximaImagem, intervalo);
    }
  }

  componentWillUnmount() {
    if (this.intervaloId) {
      clearInterval(this.intervaloId);
    }
  }

  proximaImagem = () => {
    const { imagens } = this.props;
    this.setState((prevState) => ({
      indiceAtual: (prevState.indiceAtual + 1) % imagens.length,
    }));
  };

  imagemAnterior = () => {
    const { imagens } = this.props;
    this.setState((prevState) => ({
      indiceAtual: prevState.indiceAtual === 0 ? imagens.length - 1 : prevState.indiceAtual - 1,
    }));
  };

  irParaImagem = (indice: number) => {
    this.setState({ indiceAtual: indice });
  };

  render() {
    const { imagens, altura = '450px' } = this.props;
    const { indiceAtual } = this.state;

    if (!imagens || imagens.length === 0) {
      return null;
    }

    const imagemAtual = imagens[indiceAtual];

    const containerStyle: CSS = {
      position: 'relative',
      width: '100%',
      height: altura,
      overflow: 'hidden',
      borderRadius: '12px',
      marginBottom: '60px',
    };

    const imagemStyle: CSS = {
      width: '100%',
      height: '100%',
      objectFit: 'cover',
      transition: 'opacity 0.5s ease-in-out',
    };

    const overlayStyle: CSS = {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      background: 'linear-gradient(to top, rgba(0,0,0,0.8) 0%, rgba(0,0,0,0) 100%)',
      padding: '40px 30px 20px',
      color: '#ffffff',
    };

    const botaoStyle: CSS = {
      position: 'absolute',
      top: '50%',
      transform: 'translateY(-50%)',
      backgroundColor: 'rgba(122, 138, 106, 0.9)',
      color: '#ffffff',
      border: 'none',
      borderRadius: '50%',
      width: '50px',
      height: '50px',
      cursor: 'pointer',
      fontSize: '24px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 10,
      transition: 'background-color 0.3s',
    };

    const botaoEsquerdoStyle: CSS = {
      ...botaoStyle,
      left: '20px',
    };

    const botaoDireitoStyle: CSS = {
      ...botaoStyle,
      right: '20px',
    };

    const indicadoresStyle: CSS = {
      position: 'absolute',
      bottom: '20px',
      left: '50%',
      transform: 'translateX(-50%)',
      display: 'flex',
      gap: '10px',
      zIndex: 10,
    };

    const indicadorStyle = (ativo: boolean): CSS => ({
      width: '12px',
      height: '12px',
      borderRadius: '50%',
      backgroundColor: ativo ? '#ffffff' : 'rgba(255, 255, 255, 0.4)',
      border: 'none',
      cursor: 'pointer',
      transition: 'background-color 0.3s',
    });

    return (
      <div style={containerStyle}>
        <img
          src={imagemAtual.url}
          alt={imagemAtual.titulo || `Imagem ${indiceAtual + 1}`}
          style={imagemStyle}
        />

        {(imagemAtual.titulo || imagemAtual.legenda) && (
          <div style={overlayStyle}>
            {imagemAtual.titulo && (
              <h3 style={{ fontSize: '32px', marginBottom: '8px', fontWeight: 'bold' }}>
                {imagemAtual.titulo}
              </h3>
            )}
            {imagemAtual.legenda && (
              <p style={{ fontSize: '14.5px', lineHeight: '1.5' }}>
                {imagemAtual.legenda}
              </p>
            )}
          </div>
        )}

        {imagens.length > 1 && (
          <>
            <button
              style={botaoEsquerdoStyle}
              onClick={this.imagemAnterior}
              onMouseEnter={(e) => {
                (e.currentTarget as HTMLButtonElement).style.backgroundColor = 'rgba(122, 138, 106, 1)';
              }}
              onMouseLeave={(e) => {
                (e.currentTarget as HTMLButtonElement).style.backgroundColor = 'rgba(122, 138, 106, 0.9)';
              }}
            >
              ‹
            </button>

            <button
              style={botaoDireitoStyle}
              onClick={this.proximaImagem}
              onMouseEnter={(e) => {
                (e.currentTarget as HTMLButtonElement).style.backgroundColor = 'rgba(122, 138, 106, 1)';
              }}
              onMouseLeave={(e) => {
                (e.currentTarget as HTMLButtonElement).style.backgroundColor = 'rgba(122, 138, 106, 0.9)';
              }}
            >
              ›
            </button>

            <div style={indicadoresStyle}>
              {imagens.map((_, index) => (
                <button
                  key={index}
                  style={indicadorStyle(index === indiceAtual)}
                  onClick={() => this.irParaImagem(index)}
                />
              ))}
            </div>
          </>
        )}
      </div>
    );
  }
}

// src/components/CarrosselImagens.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';

  export let imagens: any[] = [];
  export let altura: string = '400px';
  export let autoPlay: boolean = true;
  export let intervalo: number = 5000;

  let indiceAtual: number = 0;
  let timerId: ReturnType<typeof setInterval> | null = null;
  let isTransitioning: boolean = false;

  $: totalImagens = imagens.length;
  $: imagemAtual = imagens[indiceAtual] || null;

  function proximo() {
    if (totalImagens === 0) return;
    isTransitioning = true;
    indiceAtual = (indiceAtual + 1) % totalImagens;
    resetTimer();
  }

  function anterior() {
    if (totalImagens === 0) return;
    isTransitioning = true;
    indiceAtual = (indiceAtual - 1 + totalImagens) % totalImagens;
    resetTimer();
  }

  function irPara(i: number) {
    if (i === indiceAtual) return;
    isTransitioning = true;
    indiceAtual = i;
    resetTimer();
  }

  function iniciarTimer() {
    if (!autoPlay || totalImagens <= 1) return;
    timerId = setInterval(proximo, intervalo);
  }

  function pararTimer() {
    if (timerId) {
      clearInterval(timerId);
      timerId = null;
    }
  }

  function resetTimer() {
    pararTimer();
    iniciarTimer();
  }

  function handleTransitionEnd() {
    isTransitioning = false;
  }

  onMount(() => {
    iniciarTimer();
  });

  onDestroy(() => {
    pararTimer();
  });
</script>

<div class="carrossel" style="height: {altura};">
  {#if totalImagens > 0}
    <div class="slides-container">
      {#each imagens as img, i}
        <div
          class="slide"
          class:active={i === indiceAtual}
          on:transitionend={handleTransitionEnd}
        >
          <img src={img.url} alt={img.titulo || 'Imagem'} class="slide-img" />
        </div>
      {/each}
    </div>

    {#if totalImagens > 1}
      <button class="btn-nav btn-prev" on:click={anterior} aria-label="Anterior">&#10094;</button>
      <button class="btn-nav btn-next" on:click={proximo} aria-label="Próximo">&#10095;</button>

      <div class="dots">
        {#each imagens as _, i}
          <button
            class="dot"
            class:active={i === indiceAtual}
            on:click={() => irPara(i)}
            aria-label="Ir para imagem {i + 1}"
          ></button>
        {/each}
      </div>
    {/if}
  {:else}
    <div class="placeholder">
      <p>Nenhuma imagem disponível</p>
    </div>
  {/if}
</div>

{#if totalImagens > 0 && imagens[indiceAtual] && (imagens[indiceAtual].titulo || imagens[indiceAtual].legenda)}
  <div class="caption-externo">
    {#if imagens[indiceAtual].titulo}
      <h3 class="caption-titulo-externo">{imagens[indiceAtual].titulo}</h3>
    {/if}
    {#if imagens[indiceAtual].legenda}
      <p class="caption-legenda-externo">{imagens[indiceAtual].legenda}</p>
    {/if}
  </div>
{/if}

<style>
  .carrossel {
    position: relative;
    width: 100%;
    overflow: hidden;
    border-radius: 12px;
    margin-bottom: 20px;
  }

  .caption-externo {
    text-align: center;
    margin-bottom: 40px;
    color: #4a5d3c;
  }

  .caption-titulo-externo {
    margin: 0 0 8px 0;
    font-size: 24px;
    font-weight: bold;
  }

  .caption-legenda-externo {
    margin: 0;
    font-size: 16px;
    color: #666;
  }

  .slides-container {
    position: relative;
    width: 100%;
    height: 100%;
  }

  .slide {
    position: absolute;
    inset: 0;
    opacity: 0;
    transition: opacity 0.5s ease-in-out;
    z-index: 0;
  }

  .slide.active {
    opacity: 1;
    z-index: 1;
  }

  .slide-img {
    width: 100%;
    height: 100%;
    object-fit: contain;
    background-color: #4a5d3c;
    transition: opacity 0.5s ease-in-out;
  }

  .overlay-gradient {
    display: none; /* Combined with caption in TSX */
  }

  .caption {
    position: absolute;
    bottom: 0;
    left: 0;
    right: 0;
    background: linear-gradient(to top, rgba(0,0,0,0.8) 0%, rgba(0,0,0,0) 100%);
    padding: 40px 30px 20px;
    color: #ffffff;
    z-index: 2;
  }

  .caption-titulo {
    margin: 0;
    margin-bottom: 8px;
    font-size: 32px;
    font-weight: bold;
  }

  .caption-legenda {
    margin: 0;
    font-size: 14.5px;
    line-height: 1.5;
  }

  .btn-nav {
    position: absolute;
    top: 50%;
    transform: translateY(-50%);
    z-index: 10;
    background-color: rgba(122, 138, 106, 0.9);
    color: #ffffff;
    border: none;
    border-radius: 50%;
    width: 50px;
    height: 50px;
    cursor: pointer;
    font-size: 24px;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: background-color 0.3s;
    padding: 0;
  }

  .btn-nav:hover {
    background-color: rgba(122, 138, 106, 1);
  }

  .btn-prev {
    left: 20px;
  }

  .btn-next {
    right: 20px;
  }

  .dots {
    position: absolute;
    bottom: 20px;
    left: 50%;
    transform: translateX(-50%);
    display: flex;
    gap: 10px;
    z-index: 10;
  }

  .dot {
    width: 12px;
    height: 12px;
    border-radius: 50%;
    background-color: rgba(255, 255, 255, 0.4);
    border: none;
    cursor: pointer;
    transition: background-color 0.3s;
    padding: 0;
  }

  .dot.active {
    background-color: #ffffff;
  }

  .placeholder {
    display: flex;
    align-items: center;
    justify-content: center;
    height: 100%;
    color: #888;
    font-size: 1rem;
  }
</style>
