// src/app/components/FormImagemCarrossel.tsx
import React from 'react';
import { ImagemCarrosselModel } from '../models/ImagemCarrosselModel';
import { controllerCriarImagemCarrossel, controllerAtualizarImagemCarrossel } from '../controllers/ImagemCarrosselController';
import { controllerUploadImagem } from '../controllers/UploadController';

type CSS = React.CSSProperties;

const overlayStyle: CSS = {
  position: 'fixed',
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
  backgroundColor: 'rgba(0, 0, 0, 0.7)',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  zIndex: 1002,
  overflowY: 'auto',
  padding: '20px',
};

const modalStyle: CSS = {
  backgroundColor: '#ffffff',
  padding: '40px',
  borderRadius: '8px',
  maxWidth: '600px',
  width: '100%',
};

const titleStyle: CSS = {
  margin: '0 0 25px 0',
  color: '#4a5d3c',
  fontSize: '28px',
};

const formGroupStyle: CSS = {
  marginBottom: '20px',
};

const labelStyle: CSS = {
  display: 'block',
  marginBottom: '8px',
  color: '#4a5d3c',
  fontSize: '14px',
  fontWeight: 'bold',
};

const inputStyle: CSS = {
  width: '100%',
  padding: '10px',
  border: '2px solid #e8ddc5',
  borderRadius: '4px',
  fontSize: '14px',
  boxSizing: 'border-box',
};

const textareaStyle: CSS = Object.assign({}, inputStyle, {
  minHeight: '80px',
  resize: 'vertical',
});

const buttonContainerStyle: CSS = {
  display: 'flex',
  gap: '10px',
  justifyContent: 'flex-end',
  marginTop: '30px',
};

const saveButtonStyle: CSS = {
  padding: '12px 24px',
  backgroundColor: '#4a5d3c',
  color: '#ffffff',
  border: 'none',
  borderRadius: '4px',
  cursor: 'pointer',
  fontSize: '14px',
  fontWeight: 'bold',
};

const cancelButtonStyle: CSS = {
  padding: '12px 24px',
  backgroundColor: '#ffffff',
  color: '#4a5d3c',
  border: '2px solid #4a5d3c',
  borderRadius: '4px',
  cursor: 'pointer',
  fontSize: '14px',
  fontWeight: 'bold',
};

export class FormImagemCarrossel extends React.Component<{
  imagem: ImagemCarrosselModel | null;
  onClose: () => void;
  onSuccess: () => void;
}> {
  state = {
    url: '',
    titulo: '',
    legenda: '',
    ordem: 1,
    salvando: false,
    file: null as File | null,
    previewUrl: '',
  };

  componentDidMount() {
    const { imagem } = this.props;
    if (imagem) {
      this.setState({
        url: imagem.url,
        titulo: imagem.titulo,
        legenda: imagem.legenda,
        ordem: imagem.ordem,
      });
    }
  }

  handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const file = e.target.files[0];
      const previewUrl = URL.createObjectURL(file);
      this.setState({ file, previewUrl });
    }
  };

  handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    this.setState({ salvando: true });

    let url = this.state.url;

    if (this.state.file) {
      try {
        url = await controllerUploadImagem(this.state.file);
      } catch (err) {
        alert('Erro no upload da imagem');
        this.setState({ salvando: false });
        return;
      }
    }

    const imagemData = new ImagemCarrosselModel();
    imagemData.url = url;
    imagemData.titulo = this.state.titulo;
    imagemData.legenda = this.state.legenda;
    imagemData.ordem = this.state.ordem;

    try {
      if (this.props.imagem) {
        imagemData.id = this.props.imagem.id;
        await controllerAtualizarImagemCarrossel(imagemData);
      } else {
        await controllerCriarImagemCarrossel(imagemData);
      }
      this.props.onSuccess();
      this.props.onClose();
    } catch (err) {
      alert('Erro ao salvar imagem');
    } finally {
      this.setState({ salvando: false });
    }
  };

  render() {
    const { onClose, imagem } = this.props;

    return (
      <div style={overlayStyle}>
        <div style={modalStyle} onClick={(e) => e.stopPropagation()}>
          <h2 style={titleStyle}>{imagem ? 'Editar Imagem' : 'Nova Imagem'}</h2>

          <form onSubmit={this.handleSubmit}>
            <div style={formGroupStyle}>
              <label style={labelStyle}>Imagem *</label>
              <input
                type="file"
                accept="image/*"
                style={inputStyle}
                onChange={this.handleFileChange}
                required={!this.state.url && !this.state.file}
              />
              {this.state.salvando && this.state.file && <span style={{fontSize: '12px', color: '#666'}}>Enviando imagem...</span>}
              {(this.state.previewUrl || this.state.url) && (
                <div style={{marginTop: 10}}>
                  <img src={this.state.previewUrl || this.state.url} style={{maxWidth: '100px'}} alt="Preview" />
                </div>
              )}
            </div>

            <div style={formGroupStyle}>
              <label style={labelStyle}>Título *</label>
              <input
                type="text"
                style={inputStyle}
                value={this.state.titulo}
                onChange={(e) => this.setState({ titulo: e.target.value })}
                required
                placeholder="Título da imagem"
              />
            </div>

            <div style={formGroupStyle}>
              <label style={labelStyle}>Legenda *</label>
              <textarea
                style={textareaStyle}
                value={this.state.legenda}
                onChange={(e) => this.setState({ legenda: e.target.value })}
                required
                placeholder="Descrição da imagem"
              />
            </div>

            <div style={formGroupStyle}>
              <label style={labelStyle}>Ordem de Exibição *</label>
              <input
                type="number"
                style={inputStyle}
                value={this.state.ordem}
                onChange={(e) => this.setState({ ordem: parseInt(e.target.value) || 1 })}
                required
                min="1"
              />
            </div>

            <div style={buttonContainerStyle}>
              <button type="button" style={cancelButtonStyle} onClick={onClose}>
                Cancelar
              </button>
              <button type="submit" style={saveButtonStyle} disabled={this.state.salvando}>
                {this.state.salvando ? 'Salvando...' : 'Salvar'}
              </button>
            </div>
          </form>
        </div>
      </div>
    );
  }
}

// src/components/FormImagemCarrossel.svelte
<script lang="ts">
  import { createEventDispatcher, onMount } from "svelte";
  import { createImagemCarrosselModel } from "../models/ImagemCarrosselModel";
  import {
    controllerCriarImagemCarrossel,
    controllerAtualizarImagemCarrossel,
  } from "../controllers/ImagemCarrosselController";
  import { controllerUploadImagem } from "../controllers/UploadController";

  export let imagem: any = null;

  const dispatch = createEventDispatcher();

  let url: string = "";
  let imagemFile: File | null = null;
  let imagemPreview: string = "";
  let titulo: string = "";
  let legenda: string = "";
  let ordem: number = 0;
  let loading: boolean = false;
  let erro: string = "";
  let overlayEl: HTMLDivElement | undefined = undefined;

  $: isEditing = imagem !== null && imagem !== undefined;

  onMount(() => {
    if (imagem) {
      url = imagem.url || "";
      imagemPreview = imagem.url || "";
      titulo = imagem.titulo || "";
      legenda = imagem.legenda || "";
      ordem = imagem.ordem || 0;
    }
  });

  function handleClose() {
    dispatch("close");
  }

  function handleOverlayClick(e: MouseEvent) {
    if (e.target === overlayEl) {
      handleClose();
    }
  }

  function onDocumentKeydown(e: KeyboardEvent) {
    if (e.key === "Escape") {
      handleClose();
    }
  }

  function handleFileChange(e: Event) {
    const file = (e.target as HTMLInputElement).files?.[0];
    if (file) {
      imagemFile = file;
      const reader = new FileReader();
      reader.onload = function (ev: ProgressEvent<FileReader>) {
        imagemPreview = ev.target?.result as string;
      };
      reader.readAsDataURL(file);
    }
  }

  function removeImagem() {
    imagemFile = null;
    imagemPreview = "";
    url = "";
  }

  function validateForm() {
    if (!imagemPreview && !url) {
      erro = "Uma imagem é obrigatória.";
      return false;
    }
    if (!titulo.trim()) {
      erro = "O título é obrigatório.";
      return false;
    }
    return true;
  }

  async function handleSubmit() {
    if (!validateForm()) return;

    loading = true;
    erro = "";

    try {
      let uploadedUrl = url;

      if (imagemFile) {
        try {
          const uploadResult = await controllerUploadImagem(imagemFile);
          uploadedUrl = uploadResult;
        } catch (uploadErr) {
          erro = "Erro ao enviar imagem. Tente novamente.";
          loading = false;
          return;
        }
      }

      const model = createImagemCarrosselModel({
        url: uploadedUrl || "",
        titulo: titulo.trim(),
        legenda: legenda.trim(),
        ordem: ordem,
      });

      let resultado;
      if (isEditing) {
        model.id = imagem.id;
        resultado = await controllerAtualizarImagemCarrossel(model);
      } else {
        resultado = await controllerCriarImagemCarrossel(model);
      }

      if (resultado && resultado.sucesso !== false) {
        dispatch("success");
        handleClose();
      } else {
        erro = (resultado && resultado.mensagem) || "Erro ao salvar imagem.";
      }
    } catch (err) {
      erro = err.message || "Erro ao salvar imagem. Tente novamente.";
    } finally {
      loading = false;
    }
  }

  onMount(() => {
    document.addEventListener("keydown", onDocumentKeydown);
    return () => {
      document.removeEventListener("keydown", onDocumentKeydown);
    };
  });
</script>

<div class="overlay" bind:this={overlayEl} on:click={handleOverlayClick}>
  <div class="modal" on:click|stopPropagation>
    <button class="close-btn" on:click={handleClose} aria-label="Fechar"
      >&times;</button
    >

    <h2 class="modal-title">
      {isEditing ? "Editar Imagem do Carrossel" : "Nova Imagem do Carrossel"}
    </h2>

    {#if erro}
      <div class="error-msg">{erro}</div>
    {/if}

    <form on:submit|preventDefault={handleSubmit}>
      <div class="field">
        <label>Imagem *</label>
        {#if imagemPreview}
          <div class="image-preview-container">
            <img src={imagemPreview} alt="Preview" class="image-preview" />
            <button
              type="button"
              class="btn-remove-image"
              on:click={removeImagem}
              disabled={loading}>&times;</button
            >
          </div>
        {/if}
        <input
          type="file"
          accept="image/*"
          on:change={handleFileChange}
          disabled={loading}
          class="file-input"
        />
      </div>

      <div class="field">
        <label for="carrossel-titulo">Título *</label>
        <input
          id="carrossel-titulo"
          type="text"
          bind:value={titulo}
          placeholder="Título da imagem"
          disabled={loading}
        />
      </div>

      <div class="field">
        <label for="carrossel-legenda">Legenda</label>
        <textarea
          id="carrossel-legenda"
          bind:value={legenda}
          placeholder="Legenda descritiva da imagem"
          disabled={loading}
          rows="2"
        ></textarea>
      </div>

      <div class="field">
        <label for="carrossel-ordem">Ordem (Opcional)</label>
        <input
          id="carrossel-ordem"
          type="number"
          bind:value={ordem}
          placeholder="0"
          disabled={loading}
          min="0"
        />
      </div>

      <div class="btn-group">
        <button
          type="button"
          class="btn-cancel"
          on:click={handleClose}
          disabled={loading}>Cancelar</button
        >
        <button type="submit" class="btn-submit" disabled={loading}>
          {#if loading}
            <span class="spinner"></span> Salvando...
          {:else}
            {isEditing ? "Atualizar" : "Criar"}
          {/if}
        </button>
      </div>
    </form>
  </div>
</div>

<style>
  .overlay {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: rgba(0, 0, 0, 0.7);
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 1002;
    overflow-y: auto;
    padding: 20px;
  }

  .modal {
    background-color: #ffffff;
    padding: 40px;
    border-radius: 8px;
    max-width: 1200px;
    width: 100%;
    position: relative;
  }

  .close-btn {
    position: absolute;
    top: 20px;
    right: 20px;
    background: none;
    border: none;
    font-size: 24px;
    cursor: pointer;
    color: #4a5d3c;
    font-weight: bold;
  }

  .modal-title {
    margin: 0 0 25px 0;
    color: #4a5d3c;
    font-size: 28px;
    font-weight: bold;
  }

  .error-msg {
    background: #fef2f2;
    border: 1px solid #fca5a5;
    color: #dc2626;
    padding: 10px 14px;
    border-radius: 4px;
    font-size: 14px;
    margin-bottom: 20px;
  }

  .field {
    margin-bottom: 20px;
  }

  .field label {
    display: block;
    margin-bottom: 8px;
    color: #4a5d3c;
    font-size: 14px;
    font-weight: bold;
  }

  .field input,
  .field textarea,
  .field select {
    width: 100%;
    padding: 10px;
    border: 2px solid #e8ddc5;
    border-radius: 4px;
    font-size: 14px;
    box-sizing: border-box;
    font-family: inherit;
    background-color: #ffffff;
  }

  .field input:focus,
  .field textarea:focus,
  .field select:focus {
    outline: none;
    border-color: #4a5d3c;
  }

  .field input:disabled,
  .field textarea:disabled,
  .field select:disabled {
    background: #f3f4f6;
    cursor: not-allowed;
  }

  .field textarea {
    min-height: 80px;
    resize: vertical;
  }

  .image-preview-container {
    position: relative;
    margin-bottom: 10px;
    width: fit-content;
  }

  .image-preview {
    max-width: 100px;
    display: block;
  }

  .btn-remove-image {
    position: absolute;
    top: -8px;
    right: -8px;
    background: #dc2626;
    color: #fff;
    border: none;
    border-radius: 50%;
    width: 20px;
    height: 20px;
    font-size: 12px;
    line-height: 1;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .file-input {
    width: 100%;
    padding: 10px;
    border: 2px solid #e8ddc5;
    border-radius: 4px;
    font-size: 14px;
    box-sizing: border-box;
  }

  .btn-group {
    display: flex;
    gap: 10px;
    justify-content: flex-end;
    margin-top: 30px;
  }

  .btn-cancel {
    padding: 12px 24px;
    background-color: #ffffff;
    color: #4a5d3c;
    border: 2px solid #4a5d3c;
    border-radius: 4px;
    font-size: 14px;
    font-weight: bold;
    cursor: pointer;
  }

  .btn-cancel:disabled {
    opacity: 0.7;
    cursor: not-allowed;
  }

  .btn-submit {
    padding: 12px 24px;
    background-color: #4a5d3c;
    color: #ffffff;
    border: none;
    border-radius: 4px;
    font-size: 14px;
    font-weight: bold;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 8px;
  }

  .btn-submit:disabled {
    opacity: 0.7;
    cursor: not-allowed;
  }

  .spinner {
    display: inline-block;
    width: 14px;
    height: 14px;
    border: 2px solid rgba(255, 255, 255, 0.3);
    border-top-color: #ffffff;
    border-radius: 50%;
    animation: spin 0.6s linear infinite;
  }

  @keyframes spin {
    to {
      transform: rotate(360deg);
    }
  }
</style>
