// src/app/components/FormEquipe.tsx
import React from 'react';
import { MembroEquipeModel } from '../models/MembroEquipeModel';
import { controllerCriarMembro, controllerAtualizarMembro } from '../controllers/MembroEquipeController';
import { controllerUploadImagem } from '../controllers/UploadController';

type CSS = React.CSSProperties;

const overlayStyle: CSS = {
  position: 'fixed',
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
  backgroundColor: 'rgba(0, 0, 0, 0.7)',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  zIndex: 1002,
  overflowY: 'auto',
  padding: '20px',
};

const modalStyle: CSS = {
  backgroundColor: '#ffffff',
  padding: '40px',
  borderRadius: '8px',
  maxWidth: '700px',
  width: '100%',
  maxHeight: '90vh',
  overflowY: 'auto',
};

const titleStyle: CSS = {
  margin: '0 0 25px 0',
  color: '#4a5d3c',
  fontSize: '28px',
};

const labelStyle: CSS = {
  display: 'block',
  marginBottom: '8px',
  color: '#4a5d3c',
  fontWeight: 'bold',
  fontSize: '14px',
};

const inputStyle: CSS = {
  width: '100%',
  padding: '12px',
  marginBottom: '20px',
  border: '2px solid #e8ddc5',
  borderRadius: '4px',
  fontSize: '14px',
  boxSizing: 'border-box',
};

const textareaStyle: CSS = {
  width: '100%',
  padding: '12px',
  marginBottom: '20px',
  border: '2px solid #e8ddc5',
  borderRadius: '4px',
  fontSize: '14px',
  boxSizing: 'border-box',
  minHeight: '100px',
  fontFamily: 'inherit',
};

const buttonContainerStyle: CSS = {
  display: 'flex',
  gap: '10px',
  marginTop: '30px',
};

const buttonStyle: CSS = {
  flex: 1,
  padding: '14px',
  border: 'none',
  borderRadius: '4px',
  fontSize: '16px',
  cursor: 'pointer',
  backgroundColor: '#4a5d3c',
  color: '#ffffff',
  fontWeight: 'bold',
};

const cancelButtonStyle: CSS = {
  flex: 1,
  padding: '14px',
  border: '2px solid #4a5d3c',
  borderRadius: '4px',
  fontSize: '16px',
  cursor: 'pointer',
  backgroundColor: '#ffffff',
  color: '#4a5d3c',
  fontWeight: 'bold',
};

export class FormEquipe extends React.Component<{
  membro: MembroEquipeModel | null;
  onClose: () => void;
  onSuccess: () => void;
}> {
  state = {
    membro: this.props.membro || new MembroEquipeModel(),
    carregando: false,
    file: null as File | null,
    previewUrl: '',
  };

  componentDidMount() {
    if (!this.state.membro.fotoUrl) {
      const novoMembro = Object.assign(new MembroEquipeModel(), this.state.membro, {
        fotoUrl: 'figma:asset/ec0999868796dce3fdbedb6a94e5eab9bbc5051e.png',
      });
      this.setState({ membro: novoMembro });
    }
  }

  handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const file = e.target.files[0];
      const previewUrl = URL.createObjectURL(file);
      this.setState({ file, previewUrl });
    }
  };

  handleSalvar = async () => {
    this.setState({ carregando: true });

    let fotoUrl = this.state.membro.fotoUrl;

    if (this.state.file) {
      try {
        fotoUrl = await controllerUploadImagem(this.state.file);
      } catch (err) {
        alert('Erro no upload da imagem');
        this.setState({ carregando: false });
        return;
      }
    }

    const membroParaSalvar = Object.assign(new MembroEquipeModel(), this.state.membro, { fotoUrl });

    if (membroParaSalvar.id) {
      await controllerAtualizarMembro(membroParaSalvar.id, membroParaSalvar);
    } else {
      await controllerCriarMembro(membroParaSalvar);
    }

    this.setState({ carregando: false });
    this.props.onSuccess();
    this.props.onClose();
  };

  updateField = (field: keyof MembroEquipeModel, value: any) => {
    this.setState({
      membro: Object.assign(new MembroEquipeModel(), this.state.membro, {
        [field]: value,
      }),
    });
  };

  render() {
    const { onClose } = this.props;
    const { membro, carregando } = this.state;

    return (
      <div style={overlayStyle} onClick={onClose}>
        <div style={modalStyle} onClick={(e) => e.stopPropagation()}>
          <h2 style={titleStyle}>
            {membro.id ? 'Editar Membro' : 'Novo Membro'}
          </h2>

          <label style={labelStyle}>Nome</label>
          <input
            type="text"
            style={inputStyle}
            value={membro.nome}
            onChange={(e) => this.updateField('nome', e.target.value)}
          />

          <label style={labelStyle}>Cargo</label>
          <input
            type="text"
            style={inputStyle}
            value={membro.cargo}
            onChange={(e) => this.updateField('cargo', e.target.value)}
          />

          <label style={labelStyle}>Instituição</label>
          <input
            type="text"
            style={inputStyle}
            value={membro.instituicao}
            onChange={(e) => this.updateField('instituicao', e.target.value)}
          />

          <label style={labelStyle}>Email</label>
          <input
            type="email"
            style={inputStyle}
            value={membro.email}
            onChange={(e) => this.updateField('email', e.target.value)}
          />

          <label style={labelStyle}>Currículo Lattes</label>
          <input
            type="text"
            style={inputStyle}
            value={membro.lattes}
            onChange={(e) => this.updateField('lattes', e.target.value)}
            placeholder="http://lattes.cnpq.br/..."
          />

          <label style={labelStyle}>Foto *</label>
          <input
            type="file"
            accept="image/*"
            style={inputStyle}
            onChange={this.handleFileChange}
          />
          {this.state.carregando && this.state.file && <span style={{fontSize: '12px', color: '#666'}}>Enviando imagem...</span>}
          {(this.state.previewUrl || (membro.fotoUrl && !membro.fotoUrl.startsWith('figma'))) && (
            <div style={{marginBottom: 20}}>
              <img src={this.state.previewUrl || membro.fotoUrl} style={{maxWidth: '100px'}} alt="Preview" />
            </div>
          )}

          <label style={{ ...labelStyle, display: 'flex', alignItems: 'center', gap: '8px', cursor: 'pointer', marginBottom: '10px' }}>
            <input
              type="checkbox"
              checked={membro.comite || false}
              onChange={(e) => this.updateField('comite', e.target.checked)}
            />
            Faz parte do Comitê Gestor?
          </label>

          <label style={{ ...labelStyle, display: 'flex', alignItems: 'center', gap: '8px', cursor: 'pointer', marginBottom: '20px' }}>
            <input
              type="checkbox"
              checked={membro.pesquisador || false}
              onChange={(e) => this.updateField('pesquisador', e.target.checked)}
            />
            Também é um pesquisador?
          </label>

          {membro.comite && (
            <>
              <label style={labelStyle}>Ordem no Comitê</label>
              <input
                type="number"
                style={inputStyle}
                value={membro.ordemComite || ''}
                onChange={(e) => this.updateField('ordemComite', parseInt(e.target.value) || 0)}
              />
            </>
          )}

          <label style={labelStyle}>Descrição</label>
          <textarea
            style={textareaStyle}
            value={membro.descricao}
            onChange={(e) => this.updateField('descricao', e.target.value)}
          />

          <div style={buttonContainerStyle}>
            <button
              style={cancelButtonStyle}
              onClick={onClose}
              disabled={carregando}
            >
              Cancelar
            </button>
            <button
              style={buttonStyle}
              onClick={this.handleSalvar}
              disabled={carregando}
            >
              {carregando ? 'Salvando...' : 'Salvar'}
            </button>
          </div>
        </div>
      </div>
    );
  }
}

// src/components/FormEquipe.svelte
<script lang="ts">
  import { createEventDispatcher, onMount } from "svelte";
  import { createMembroEquipeModel } from "../models/MembroEquipeModel";
  import {
    controllerCriarMembro,
    controllerAtualizarMembro,
  } from "../controllers/MembroEquipeController";
  import { controllerUploadImagem } from "../controllers/UploadController";

  export let membro: any = null;

  const dispatch = createEventDispatcher();

  let nome: string = "";
  let cargo: string = "";
  let instituicao: string = "";
  let email: string = "";
  let lattes: string = "";
  let fotoUrl: string = "";
  let fotoFile: File | null = null;
  let fotoPreview: string = "";
  let comite: boolean = false;
  let pesquisador: boolean = false;
  let ordemComite: number | undefined = undefined;
  let descricao: string = "";
  let loading: boolean = false;
  let erro: string = "";
  let overlayEl: HTMLDivElement | undefined = undefined;

  $: isEditing = membro !== null && membro !== undefined;

  onMount(() => {
    if (membro) {
      nome = membro.nome || "";
      cargo = membro.cargo || "";
      instituicao = membro.instituicao || "";
      email = membro.email || "";
      lattes = membro.lattes || "";
      fotoUrl = membro.fotoUrl || "";
      fotoPreview = membro.fotoUrl || "";
      comite = membro.comite || false;
      pesquisador = membro.pesquisador || false;
      ordemComite = membro.ordemComite || undefined;
      descricao = membro.descricao || "";
    }
  });

  function handleClose() {
    dispatch("close");
  }

  function handleOverlayClick(e: MouseEvent) {
    if (e.target === overlayEl) {
      handleClose();
    }
  }

  function onDocumentKeydown(e: KeyboardEvent) {
    if (e.key === "Escape") {
      handleClose();
    }
  }

  function handleFileChange(e: Event) {
    const file = (e.target as HTMLInputElement).files?.[0];
    if (file) {
      fotoFile = file;
      const reader = new FileReader();
      reader.onload = function (ev: ProgressEvent<FileReader>) {
        fotoPreview = ev.target?.result as string;
      };
      reader.readAsDataURL(file);
    }
  }

  function removeFoto() {
    fotoFile = null;
    fotoPreview = "";
    fotoUrl = "";
  }

  function validateForm() {
    if (!nome.trim()) {
      erro = "O nome é obrigatório.";
      return false;
    }
    if (!cargo.trim()) {
      erro = "O cargo é obrigatório.";
      return false;
    }
    return true;
  }

  async function handleSubmit() {
    if (!validateForm()) return;

    loading = true;
    erro = "";

    try {
      let uploadedUrl = fotoUrl;

      if (fotoFile) {
        try {
          const uploadResult = await controllerUploadImagem(fotoFile);
          uploadedUrl = uploadResult;
        } catch (uploadErr) {
          erro = "Erro ao enviar foto. Tente novamente.";
          loading = false;
          return;
        }
      }

      const model = createMembroEquipeModel({
        nome: nome.trim(),
        cargo: cargo.trim(),
        instituicao: instituicao.trim(),
        email: email.trim(),
        lattes: lattes.trim(),
        fotoUrl: uploadedUrl || "",
        comite: comite,
        pesquisador: pesquisador,
        ordemComite: comite ? ordemComite || 0 : undefined,
        descricao: descricao.trim(),
      });

      let resultado;
      if (isEditing) {
        model.id = membro.id;
        resultado = await controllerAtualizarMembro(membro.id, model);
      } else {
        resultado = await controllerCriarMembro(model);
      }

      if (resultado) {
        dispatch("success");
        handleClose();
      } else {
        erro = "Erro ao salvar membro.";
      }
    } catch (err) {
      erro = err.message || "Erro ao salvar membro. Tente novamente.";
    } finally {
      loading = false;
    }
  }

  onMount(() => {
    document.addEventListener("keydown", onDocumentKeydown);
    return () => {
      document.removeEventListener("keydown", onDocumentKeydown);
    };
  });
</script>

<div class="overlay" bind:this={overlayEl} on:click={handleOverlayClick}>
  <div class="modal" on:click|stopPropagation>
    <button class="close-btn" on:click={handleClose} aria-label="Fechar"
      >&times;</button
    >

    <h2 class="modal-title">{isEditing ? "Editar Membro" : "Novo Membro"}</h2>

    {#if erro}
      <div class="error-msg">{erro}</div>
    {/if}

    <form on:submit|preventDefault={handleSubmit}>
      <div class="field">
        <label for="equipe-nome">Nome *</label>
        <input
          id="equipe-nome"
          type="text"
          bind:value={nome}
          placeholder="Nome completo"
          disabled={loading}
        />
      </div>

      <div class="field-row">
        <div class="field">
          <label for="equipe-cargo">Cargo *</label>
          <input
            id="equipe-cargo"
            type="text"
            bind:value={cargo}
            placeholder="Ex: Líder de Pesquisa"
            disabled={loading}
          />
        </div>
        <div class="field">
          <label for="equipe-instituicao">Instituição</label>
          <input
            id="equipe-instituicao"
            type="text"
            bind:value={instituicao}
            placeholder="Ex: UFBA"
            disabled={loading}
          />
        </div>
      </div>

      <div class="field-row">
        <div class="field">
          <label for="equipe-email">Email</label>
          <input
            id="equipe-email"
            type="email"
            bind:value={email}
            placeholder="email@instituicao.br"
            disabled={loading}
          />
        </div>
        <div class="field">
          <label for="equipe-lattes">Lattes</label>
          <input
            id="equipe-lattes"
            type="url"
            bind:value={lattes}
            placeholder="http://lattes.cnpq.br/..."
            disabled={loading}
          />
        </div>
      </div>

      <div class="field">
        <label>Foto</label>
        {#if fotoPreview}
          <div class="image-preview-container">
            <img src={fotoPreview} alt="Preview" class="image-preview" />
            <button
              type="button"
              class="btn-remove-image"
              on:click={removeFoto}
              disabled={loading}>&times;</button
            >
          </div>
        {/if}
        <input
          type="file"
          accept="image/*"
          on:change={handleFileChange}
          disabled={loading}
          class="file-input"
        />
      </div>

      <div class="checkbox-group">
        <label class="checkbox-label">
          <input type="checkbox" bind:checked={comite} disabled={loading} />
          <span>Membro do Comitê Gestor</span>
        </label>
        <label class="checkbox-label">
          <input
            type="checkbox"
            bind:checked={pesquisador}
            disabled={loading}
          />
          <span>Pesquisador</span>
        </label>
      </div>

      {#if comite}
        <div class="field">
          <label for="equipe-ordem">Ordem (Opcional) no Comitê</label>
          <input
            id="equipe-ordem"
            type="number"
            bind:value={ordemComite}
            placeholder="1"
            disabled={loading}
            min="0"
          />
        </div>
      {/if}

      <div class="field">
        <label for="equipe-descricao">Descrição</label>
        <textarea
          id="equipe-descricao"
          bind:value={descricao}
          placeholder="Descrição do membro e suas pesquisas"
          disabled={loading}
          rows="3"
        ></textarea>
      </div>

      <div class="btn-group">
        <button
          type="button"
          class="btn-cancel"
          on:click={handleClose}
          disabled={loading}>Cancelar</button
        >
        <button type="submit" class="btn-submit" disabled={loading}>
          {#if loading}
            <span class="spinner"></span> Salvando...
          {:else}
            {isEditing ? "Atualizar" : "Criar"}
          {/if}
        </button>
      </div>
    </form>
  </div>
</div>

<style>
  .overlay {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: rgba(0, 0, 0, 0.7);
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 1002;
    overflow-y: auto;
    padding: 20px;
  }

  .modal {
    background-color: #ffffff;
    padding: 40px;
    border-radius: 8px;
    max-width: 1200px;
    width: 100%;
    max-height: 98vh;
    overflow-y: auto;
    position: relative;
  }

  .close-btn {
    position: absolute;
    top: 20px;
    right: 20px;
    background: none;
    border: none;
    font-size: 24px;
    cursor: pointer;
    color: #4a5d3c;
    font-weight: bold;
  }

  .modal-title {
    margin: 0 0 25px 0;
    color: #4a5d3c;
    font-size: 28px;
    font-weight: bold;
  }

  .error-msg {
    background: #fef2f2;
    border: 1px solid #fca5a5;
    color: #dc2626;
    padding: 10px 14px;
    border-radius: 4px;
    font-size: 14px;
    margin-bottom: 20px;
  }

  .field {
    margin-bottom: 0; /* Margin handled by input now */
  }

  .field label {
    display: block;
    margin-bottom: 8px;
    color: #4a5d3c;
    font-weight: bold;
    font-size: 14px;
  }

  .field input,
  .field textarea,
  .field select {
    width: 100%;
    padding: 12px;
    margin-bottom: 20px;
    border: 2px solid #e8ddc5;
    border-radius: 4px;
    font-size: 14px;
    box-sizing: border-box;
    font-family: inherit;
    background-color: #ffffff;
  }

  .field input:focus,
  .field textarea:focus,
  .field select:focus {
    outline: none;
    border-color: #4a5d3c;
  }

  .field input:disabled,
  .field textarea:disabled,
  .field select:disabled {
    background: #f3f4f6;
    cursor: not-allowed;
  }

  .field textarea {
    min-height: 100px;
    resize: vertical;
  }

  .field-row {
    display: flex;
    gap: 16px;
  }

  .field-row .field {
    flex: 1;
  }

  .image-preview-container {
    position: relative;
    margin-bottom: 20px;
    width: fit-content;
  }

  .image-preview {
    max-width: 100px;
    display: block;
  }

  .btn-remove-image {
    position: absolute;
    top: -8px;
    right: -8px;
    background: #dc2626;
    color: #fff;
    border: none;
    border-radius: 50%;
    width: 20px;
    height: 20px;
    font-size: 12px;
    line-height: 1;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .file-input {
    width: 100%;
    padding: 12px;
    border: 2px solid #e8ddc5;
    border-radius: 4px;
    font-size: 14px;
    box-sizing: border-box;
    margin-bottom: 20px;
  }

  .checkbox-group {
    display: flex;
    flex-direction: column;
    gap: 10px;
    margin-bottom: 20px;
  }

  .checkbox-label {
    display: flex;
    align-items: center;
    gap: 8px;
    color: #4a5d3c;
    font-weight: bold;
    font-size: 14px;
    cursor: pointer;
  }

  .checkbox-label input[type="checkbox"] {
    width: auto;
    margin-bottom: 0;
  }

  .btn-group {
    display: flex;
    gap: 10px;
    margin-top: 30px;
  }

  .btn-cancel {
    flex: 1;
    padding: 14px;
    border: 2px solid #4a5d3c;
    border-radius: 4px;
    font-size: 16px;
    cursor: pointer;
    background-color: #ffffff;
    color: #4a5d3c;
    font-weight: bold;
  }

  .btn-cancel:disabled {
    opacity: 0.7;
    cursor: not-allowed;
  }

  .btn-submit {
    flex: 1;
    padding: 14px;
    border: none;
    border-radius: 4px;
    font-size: 16px;
    cursor: pointer;
    background-color: #4a5d3c;
    color: #ffffff;
    font-weight: bold;
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 8px;
  }

  .btn-submit:disabled {
    opacity: 0.7;
    cursor: not-allowed;
  }

  .spinner {
    display: inline-block;
    width: 16px;
    height: 16px;
    border: 2px solid rgba(255, 255, 255, 0.3);
    border-top-color: #ffffff;
    border-radius: 50%;
    animation: spin 0.6s linear infinite;
  }

  @keyframes spin {
    to {
      transform: rotate(360deg);
    }
  }
</style>
