// src/app/components/GerenciarImagensCarrossel.tsx
import React from 'react';
import { ImagemCarrosselModel } from '../models/ImagemCarrosselModel';
import { controllerListarImagensCarrossel, controllerDeletarImagemCarrossel } from '../controllers/ImagemCarrosselController';

type CSS = React.CSSProperties;

const overlayStyle: CSS = {
  position: 'fixed',
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
  backgroundColor: 'rgba(0, 0, 0, 0.7)',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  zIndex: 1001,
  overflowY: 'auto',
  padding: '20px',
};

const modalStyle: CSS = {
  backgroundColor: '#ffffff',
  borderRadius: '8px',
  width: '90%',
  maxHeight: '95vh',
  overflowY: 'auto',
  position: 'relative',
};

const headerStyle: CSS = {
  padding: '20px 40px',
  borderBottom: '2px solid #e8ddc5',
  display: 'flex',
  justifyContent: 'space-between',
  alignItems: 'center',
  position: 'sticky',
  top: 0,
  backgroundColor: '#ffffff',
  zIndex: 10,
};

const titleStyle: CSS = {
  margin: 0,
  color: '#4a5d3c',
  fontSize: '28px',
};

const closeButtonStyle: CSS = {
  padding: '8px',
  backgroundColor: 'transparent',
  color: '#4a5d3c',
  border: 'none',
  cursor: 'pointer',
  fontSize: '24px',
  fontWeight: 'bold',
  lineHeight: 1,
};

const contentStyle: CSS = {
  padding: '20px',
};

const addButtonStyle: CSS = {
  padding: '10px 20px',
  backgroundColor: '#4a5d3c',
  color: '#ffffff',
  border: 'none',
  borderRadius: '6px',
  cursor: 'pointer',
  fontSize: '24px',
  fontWeight: 'bold',
  lineHeight: 1,
};

const gridStyle: CSS = {
  display: 'grid',
  gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
  gap: '25px',
  marginBottom: '20px',
};

const cardStyle: CSS = {
  padding: '20px',
  borderRadius: '8px',
  border: '2px solid #e8ddc5',
  backgroundColor: '#ffffff',
  transition: 'transform 0.3s, box-shadow 0.3s',
};

const actionButtonStyle: CSS = {
  padding: '6px 12px',
  margin: '0',
  border: 'none',
  borderRadius: '4px',
  cursor: 'pointer',
  fontSize: '14px',
  fontWeight: 'bold',
  transition: 'background-color 0.3s',
};

const editButtonStyle: CSS = {
  ...actionButtonStyle,
  backgroundColor: '#7a8a6a',
  color: '#ffffff',
  marginRight: '10px',
};

const deleteButtonStyle: CSS = {
  ...actionButtonStyle,
  backgroundColor: '#c44',
  color: '#ffffff',
};

export class GerenciarImagensCarrossel extends React.Component<{
  onClose: () => void;
  onEdit: (imagem: ImagemCarrosselModel) => void;
  onAdd: () => void;
  onUpdate: () => void;
}> {
  state = {
    imagens: [] as ImagemCarrosselModel[],
    carregando: true,
    isMobile: window.innerWidth <= 768,
  };

  componentDidMount() {
    this.carregarImagens();
    window.addEventListener('resize', this.handleResize);
    document.body.style.overflow = 'hidden';
  }

  componentWillUnmount() {
    window.removeEventListener('resize', this.handleResize);
    document.body.style.overflow = '';
  }

  handleResize = () => {
    this.setState({ isMobile: window.innerWidth <= 768 });
  };

  carregarImagens = async () => {
    const response = await controllerListarImagensCarrossel();
    this.setState({
      imagens: (response.response || []).sort((a, b) => a.ordem - b.ordem),
      carregando: false,
    });
  };

  handleDeletar = async (id: number, titulo: string) => {
    if (confirm(`Tem certeza que deseja deletar a imagem "${titulo}"?`)) {
      await controllerDeletarImagemCarrossel(id);
      await this.carregarImagens();
      this.props.onUpdate();
    }
  };

  render() {
    const { onClose, onAdd, onEdit } = this.props;
    const { isMobile, imagens } = this.state;

    const responsiveModalStyle = isMobile
      ? { ...modalStyle, width: '100%', height: '100%', maxHeight: '100vh', borderRadius: 0 }
      : modalStyle;

    return (
      <div style={overlayStyle}>
        <div style={responsiveModalStyle} onClick={(e) => e.stopPropagation()}>
          <div style={headerStyle}>
            <h2 style={titleStyle}>Imagens do Carrossel</h2>
            <div style={{ display: 'flex', gap: '15px', alignItems: 'center' }}>
              <button style={addButtonStyle} onClick={onAdd} title="Nova Imagem">
                +
              </button>
              <button style={closeButtonStyle} onClick={onClose}>
                ✕
              </button>
            </div>
          </div>

          <div style={contentStyle}>
            {this.state.carregando ? (
              <div style={{ textAlign: 'center', padding: '40px' }}>Carregando...</div>
            ) : (
              <div style={gridStyle}>
                {imagens.map((imagem) => (
                  <div
                    key={imagem.id}
                    style={cardStyle}
                    onMouseEnter={(e) => {
                      e.currentTarget.style.transform = 'translateY(-5px)';
                      e.currentTarget.style.boxShadow = '0 4px 12px rgba(0,0,0,0.15)';
                    }}
                    onMouseLeave={(e) => {
                      e.currentTarget.style.transform = 'translateY(0)';
                      e.currentTarget.style.boxShadow = 'none';
                    }}
                  >
                    <img
                      src={imagem.url}
                      alt={imagem.titulo}
                      style={{
                        width: '100%',
                        height: '180px',
                        objectFit: 'cover',
                        borderRadius: '6px',
                        marginBottom: '15px',
                      }}
                    />
                    <h3 style={{ marginBottom: '10px', color: '#4a5d3c' }}>
                      {imagem.titulo}
                    </h3>
                    <p style={{ fontSize: '14px', color: '#666', marginBottom: '10px' }}>
                      <strong>Legenda:</strong> {imagem.legenda}
                    </p>
                    <p style={{ fontSize: '14px', color: '#666', marginBottom: '5px' }}>
                      <strong>Ordem:</strong> {imagem.ordem}
                    </p>
                    <div style={{ display: 'flex', gap: '10px', justifyContent: 'flex-start' }}>
                      <button
                        style={editButtonStyle}
                        onClick={() => onEdit(imagem)}
                        onMouseEnter={(e) => {
                          e.currentTarget.style.backgroundColor = '#5a6a4a';
                        }}
                        onMouseLeave={(e) => {
                          e.currentTarget.style.backgroundColor = '#7a8a6a';
                        }}
                      >
                        Editar
                      </button>
                      <button
                        style={deleteButtonStyle}
                        onClick={() => this.handleDeletar(imagem.id, imagem.titulo)}
                        onMouseEnter={(e) => {
                          e.currentTarget.style.backgroundColor = '#a33';
                        }}
                        onMouseLeave={(e) => {
                          e.currentTarget.style.backgroundColor = '#c44';
                        }}
                      >
                        Excluir
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            )}

            {imagens.length === 0 && !this.state.carregando && (
              <div style={{ textAlign: 'center', padding: '40px', color: '#7a8a6a' }}>
                Nenhuma imagem encontrada
              </div>
            )}
          </div>
        </div>
      </div>
    );
  }
}

// src/components/GerenciarImagensCarrossel.svelte
<script lang="ts">
  import { createEventDispatcher, onMount } from "svelte";
  import {
    controllerListarImagensCarrossel,
    controllerDeletarImagemCarrossel,
  } from "../controllers/ImagemCarrosselController";
  import { refreshTrigger } from "../stores/appStore";

  const dispatch = createEventDispatcher();

  let imagens: any[] = [];
  let carregando: boolean = true;
  let erro: string = "";
  let confirmarDelete: any = null;
  let overlayEl: HTMLDivElement | undefined = undefined;

  onMount(async () => {
    await carregarImagens();
  });

  $: if ($refreshTrigger) {
    carregarImagens();
  }

  async function carregarImagens() {
    carregando = true;
    erro = "";
    try {
      const resultado = await controllerListarImagensCarrossel();
      const data = resultado.response || resultado || [];
      imagens = data.sort((a, b) => (a.ordem || 0) - (b.ordem || 0));
    } catch (err) {
      erro = err.message || "Erro ao carregar imagens.";
    } finally {
      carregando = false;
    }
  }

  function handleClose() {
    dispatch("close");
  }

  function handleOverlayClick(e: MouseEvent) {
    if (e.target === overlayEl) {
      handleClose();
    }
  }

  function handleEdit(imagem: any) {
    dispatch("edit", { imagem });
  }

  function handleAdd() {
    dispatch("add");
  }

  function handleUpdate() {
    dispatch("update");
    carregarImagens();
  }

  function solicitarDelete(imagem: any) {
    confirmarDelete = imagem;
  }

  function cancelarDelete() {
    confirmarDelete = null;
  }

  async function confirmarDeleteAction() {
    if (!confirmarDelete) return;
    try {
      await controllerDeletarImagemCarrossel(confirmarDelete.id);
      imagens = imagens.filter((i) => i.id !== confirmarDelete.id);
      confirmarDelete = null;
    } catch (err) {
      erro = err.message || "Erro ao deletar imagem.";
      confirmarDelete = null;
    }
  }

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === "Escape") {
      handleClose();
    }
  }
</script>

<svelte:window on:keydown={handleKeydown} />

<div class="overlay" bind:this={overlayEl} on:click={handleOverlayClick}>
  <div class="modal" on:click|stopPropagation>
    <div class="modal-header">
      <h2 class="modal-title">Gerenciar Imagens do Carrossel</h2>
      <div class="header-actions">
        <button class="btn-add" on:click={handleAdd} title="Adicionar imagem"
          >+</button
        >
        <button class="close-btn" on:click={handleClose} aria-label="Fechar"
          >&#10005;</button
        >
      </div>
    </div>

    <div class="modal-body">
      {#if carregando}
        <div class="loading">Carregando...</div>
      {:else if erro}
        <div class="error-msg">{erro}</div>
      {:else if imagens.length === 0}
        <div class="empty">Nenhuma imagem encontrada.</div>
      {:else}
        <div class="card-grid">
          {#each imagens as imagem (imagem.id)}
            <div class="card">
              <div class="card-image">
                <img
                  src={imagem.url}
                  alt={imagem.titulo || "Imagem do carrossel"}
                />
                <span class="ordem-badge">Ordem (Opcional): {imagem.ordem}</span
                >
              </div>
              <div class="card-content">
                <h3 class="card-title">{imagem.titulo}</h3>
                <p class="card-legenda">{imagem.legenda}</p>
              </div>
              <div class="card-actions">
                <button class="btn-edit" on:click={() => handleEdit(imagem)}
                  >Editar</button
                >
                <button
                  class="btn-delete"
                  on:click={() => solicitarDelete(imagem)}>Excluir</button
                >
              </div>
            </div>
          {/each}
        </div>
      {/if}
    </div>

    {#if confirmarDelete}
      <div class="confirm-overlay" on:click|stopPropagation>
        <div class="confirm-dialog">
          <p>
            Tem certeza que deseja excluir <strong
              >{confirmarDelete.titulo || "esta imagem"}</strong
            >?
          </p>
          <div class="confirm-actions">
            <button class="btn-cancel" on:click={cancelarDelete}
              >Cancelar</button
            >
            <button class="btn-confirm-delete" on:click={confirmarDeleteAction}
              >Excluir</button
            >
          </div>
        </div>
      </div>
    {/if}
  </div>
</div>

<style>
  .overlay {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: rgba(0, 0, 0, 0.7);
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 1001;
    overflow-y: auto;
    padding: 20px;
  }

  .modal {
    background-color: #ffffff;
    border-radius: 8px;
    width: 98%;
    height: 95vh;
    max-height: 98vh;
    overflow-y: auto;
    position: relative;
  }

  .modal-header {
    padding: 20px 40px;
    border-bottom: 2px solid #e8ddc5;
    display: flex;
    justify-content: space-between;
    align-items: center;
    position: sticky;
    top: 0;
    background-color: #ffffff;
    z-index: 10;
  }

  .modal-title {
    margin: 0;
    color: #4a5d3c;
    font-size: 28px;
    font-weight: bold;
  }

  .header-actions {
    display: flex;
    align-items: center;
    gap: 15px;
  }

  .btn-add {
    padding: 10px 20px;
    background-color: #4a5d3c;
    color: #ffffff;
    border: none;
    border-radius: 6px;
    cursor: pointer;
    font-size: 24px;
    font-weight: bold;
    line-height: 1;
  }

  .close-btn {
    padding: 8px;
    background-color: transparent;
    color: #4a5d3c;
    border: none;
    cursor: pointer;
    font-size: 24px;
    font-weight: bold;
    line-height: 1;
  }

  .modal-body {
    padding: 20px;
  }

  .loading,
  .empty {
    text-align: center;
    padding: 40px;
    color: #7a8a6a;
  }

  .error-msg {
    background: #fef2f2;
    border: 1px solid #fca5a5;
    color: #dc2626;
    padding: 10px 14px;
    border-radius: 4px;
    font-size: 14px;
    margin-bottom: 20px;
  }

  .card-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
    gap: 25px;
    margin-bottom: 20px;
  }

  .card {
    border-radius: 8px;
    border: 2px solid #e8ddc5;
    background-color: #ffffff;
    transition:
      transform 0.3s,
      box-shadow 0.3s;
    display: flex;
    flex-direction: column;
    overflow: hidden;
  }

  .card:hover {
    transform: translateY(-5px);
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
  }

  .card-image {
    /* For standardisation, although TSX applies these directly to img */
    position: relative;
  }

  .card-image img {
    width: 100%;
    aspect-ratio: 1 / 1;
    object-fit: cover;
    display: block;
    margin: 0;
  }

  .ordem-badge {
    position: absolute;
    top: 8px;
    right: 8px;
    background: #4a5d3c;
    color: #ffffff;
    padding: 3px 10px;
    border-radius: 12px;
    font-size: 12px; /* fallback */
    font-weight: 600;
  }

  .card-content {
    flex: 1;
    padding: 20px 20px 5px 20px;
  }

  .card-title {
    margin-bottom: 10px;
    color: #4a5d3c;
    font-size: 1.17em; /* approx h3 */
    margin-top: 0;
  }

  .card-legenda {
    font-size: 14px;
    color: #666;
    margin-top: 0;
    margin-bottom: 10px;
  }

  .card-actions {
    display: flex;
    gap: 10px;
    justify-content: flex-start;
    padding: 0 20px 20px 20px;
  }

  .btn-edit,
  .btn-delete {
    padding: 6px 12px;
    margin: 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    font-size: 14px;
    font-weight: bold;
    transition: background-color 0.3s;
  }

  .btn-edit {
    background-color: #7a8a6a;
    color: #ffffff;
    margin-right: 10px;
  }

  .btn-edit:hover {
    background-color: #5a6a4a;
  }

  .btn-delete {
    background-color: #c44;
    color: #ffffff;
  }

  .btn-delete:hover {
    background-color: #a33;
  }

  .confirm-overlay {
    position: absolute;
    inset: 0;
    background: rgba(0, 0, 0, 0.4);
    display: flex;
    align-items: center;
    justify-content: center;
    border-radius: 8px;
    z-index: 2;
  }

  .confirm-dialog {
    background: #ffffff;
    padding: 24px;
    border-radius: 8px;
    box-shadow: 0 8px 30px rgba(0, 0, 0, 0.2);
    max-width: 360px;
    width: 98%;
    height: 95vh;
    text-align: center;
  }

  .confirm-dialog p {
    margin: 0 0 16px;
    font-size: 16px;
    color: #333;
  }

  .confirm-actions {
    display: flex;
    gap: 10px;
    justify-content: center;
  }

  .btn-cancel {
    padding: 8px 20px;
    border: 2px solid #7a8a6a;
    background: #ffffff;
    color: #7a8a6a;
    border-radius: 6px;
    font-size: 14px;
    font-weight: bold;
    cursor: pointer;
    transition:
      background 0.2s,
      color 0.2s;
  }

  .btn-cancel:hover {
    background: #7a8a6a;
    color: #ffffff;
  }

  .btn-confirm-delete {
    padding: 8px 20px;
    border: 2px solid #c44;
    background: #c44;
    color: #ffffff;
    border-radius: 6px;
    font-size: 14px;
    font-weight: bold;
    cursor: pointer;
    transition: opacity 0.2s;
  }

  .btn-confirm-delete:hover {
    opacity: 0.85;
  }

  @media (max-width: 768px) {
    .modal {
      width: 100%;
      height: 100%;
      max-height: 100vh;
      border-radius: 0;
    }
  }
</style>
